[project]
name = "borgctl"
version = "0.5.1b1"
description = ""
authors = [{ name = "kmille", email = "github@androidloves.me" }]
readme = "README.md"
requires-python = ">=3.9"

[tool.poetry.dependencies]
python = "^3.11"
ruamel-yaml = "^0.18.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pdbpp>=0.12.1",
    "pytest>=8.4.2",
]

[tool.poetry.scripts]
borgctl = "borgctl.__init__:main"

[tool.setuptools.package-data]
borgctl = ["default.yml.template"]

[tool.mypy]
files = "borgctl/*.py"
strict_optional = false
local_partial_types = true
show_error_codes = true
show_error_context = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = [
    "borgctl.*",
    "ruamel.yaml.*"
]
ignore_missing_imports = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = "normal"
no_implicit_reexport = true
strict_equality = true
strict_optional = true
warn_return_any = true
warn_unused_ignores = true
